title:            ericnish.io
description:      A front-end developer's portfolio and blog
url:              # Site url.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Home
    url:          /
  - name:         Blog
    url:          /blog
  - name:         Projects
    url:          /projects
highlighter:      pygments
permalink:        /blog/:title/
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
sass:
  style: compressed
exclude:
  - vendor

collections:
  projects:
    output: false
